// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID             uuid.UUID
	OriginalUrl    string
	Slug           string
	AccessCount    int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastAccessedAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
