// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shortener.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    id,
    original_url,
    slug
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    original_url,
    slug,
    access_count,
    created_at,
    updated_at,
    last_accessed_at
`

type CreateLinkParams struct {
	ID          uuid.UUID
	OriginalUrl string
	Slug        string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ID, arg.OriginalUrl, arg.Slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Slug,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE slug = $1
`

func (q *Queries) DeleteLink(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteLink, slug)
	return err
}

const getLinkBySLug = `-- name: GetLinkBySLug :one
SELECT
    id,
    original_url,
    slug,
    access_count,
    created_at,
    updated_at,
    last_accessed_at
FROM links
WHERE slug = $1
`

func (q *Queries) GetLinkBySLug(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySLug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Slug,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const resolveAndTrackLink = `-- name: ResolveAndTrackLink :one
UPDATE links
SET
  access_count     = access_count + 1,
  last_accessed_at = now()
WHERE slug = $1
RETURNING
  id,
  original_url,
  slug,
  access_count,
  created_at,
  updated_at,
  last_accessed_at
`

func (q *Queries) ResolveAndTrackLink(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, resolveAndTrackLink, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Slug,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}
