// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shortener.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    id,
    original_url,
    slug
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    original_url,
    slug,
    access_count,
    created_at,
    updated_at,
    last_accessed_at,
    deleted_at
`

type CreateLinkParams struct {
	ID          uuid.UUID
	OriginalUrl string
	Slug        string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ID, arg.OriginalUrl, arg.Slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Slug,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT
    id,
    original_url,
    slug,
    access_count,
    created_at,
    updated_at,
    last_accessed_at,
    deleted_at
FROM links
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetLink(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Slug,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT
    id,
    original_url,
    slug,
    access_count,
    created_at,
    updated_at,
    last_accessed_at,
    deleted_at
FROM links
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.Slug,
			&i.AccessCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :exec
UPDATE links
SET
    deleted_at = now(),
    updated_at = now()
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLink(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, softDeleteLink, slug)
	return err
}
